Problem statement:-
Indian Movie Face database (IMFDB) is a large unconstrained face database consisting of 34512 images of 100 Indian actors collected from more than 100 videos. All the images are manually selected and cropped from the video frames resulting in a high degree of variability interms of scale, pose, expression, illumination, age, resolution, occlusion, and makeup. IMFDB is the first face database that provides a detailed annotation of every image in terms of age, pose, gender, expression and type of occlusion that may help other face related applications.

In [20]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [15]:
df = pd.read_csv('train.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19906 entries, 0 to 19905
Data columns (total 2 columns):
ID       19906 non-null object
Class    19906 non-null object
dtypes: object(2)
memory usage: 311.2+ KB

          ID   Class
0    377.jpg  MIDDLE
1  17814.jpg   YOUNG
2  21283.jpg  MIDDLE
3  16496.jpg   YOUNG
4   4487.jpg  MIDDLE

In [14]:
df['Class'] = df['Class'].astype('str')

In [4]:
def categorical_eda(df, hue=None):
    """Given dataframe, generate EDA of categorical data"""
    print("\nTo check: \nUnique count of non-numeric data\n")
    print(df.select_dtypes(include=['object', 'category']).nunique())
    top5(df)
    # Plot count distribution of categorical data
    for col in df.select_dtypes(include='category').columns:
        fig = sns.catplot(x=col, kind="count", data=df, hue=hue)
        fig.set_xticklabels(rotation=90)
        plt.show()

In [5]:
def eda(df):
    """Given dataframe, generate exploratory data analysis"""
    # check that input is pandas dataframe
    if type(df) != pd.core.frame.DataFrame:
        raise TypeError("Only pandas dataframe is allowed as input")

In [6]:
    if len(df[df.duplicated()]) > 0:
        print("\n***Number of duplicated entries: ", len(df[df.duplicated()]))
        display(df[df.duplicated(keep=False)].sort_values(by=list(df.columns)).head())
    else:
        print("\nNo duplicated entries found")

No duplicated entries found

In [7]:
eda(df)

In [8]:

file_handler = open("train.csv", "r") 
  
 
data = pd.read_csv(file_handler, sep = ",") 
  

file_handler.close() 
  

data.Class[data.Class == 'YOUNG'] = 1
data.Class[data.Class == 'MIDDLE'] = 2
data.Class[data.Class == 'OLD'] = 3

print(data)

              ID Class
0        377.jpg     2
1      17814.jpg     1
2      21283.jpg     2
3      16496.jpg     1
4       4487.jpg     2
...          ...   ...
19901   2482.jpg     2
19902  20085.jpg     1
19903  19663.jpg     2
19904  10132.jpg     2
19905   9896.jpg     2

[19906 rows x 2 columns]

In [9]:
data.head()

          ID Class
0    377.jpg     2
1  17814.jpg     1
2  21283.jpg     2
3  16496.jpg     1
4   4487.jpg     2

In [10]:
df.head()

          ID   Class
0    377.jpg  MIDDLE
1  17814.jpg   YOUNG
2  21283.jpg  MIDDLE
3  16496.jpg   YOUNG
4   4487.jpg  MIDDLE

In [18]:
import pandas_profiling
pandas_profiling.ProfileReport(df)

In [12]:
df.describe()

              ID   Class
count      19906   19906
unique     19906       3
top     4229.jpg  MIDDLE
freq           1   10804

In [ ]:
pandas_profiling.ProfileReport(df)

In [ ]:
df.infer_objects()

In [16]:
df["ignore"] = 0

In [17]:
df.head()

          ID   Class  ignore
0    377.jpg  MIDDLE       0
1  17814.jpg   YOUNG       0
2  21283.jpg  MIDDLE       0
3  16496.jpg   YOUNG       0
4   4487.jpg  MIDDLE       0

In [21]:
pip install nb2mail

Collecting nb2mail
  Downloading https://files.pythonhosted.org/packages/8e/01/d5bab4d57a980d7fd19a16d27007bd7bfe913b92c15921e421af701b05a2/nb2mail-0.6.tar.gz
Requirement already satisfied: jupyter in c:\users\user\anaconda3\lib\site-packages (from nb2mail) (1.0.0)
Requirement already satisfied: notebook in c:\users\user\anaconda3\lib\site-packages (from jupyter->nb2mail) (6.0.1)
Requirement already satisfied: ipywidgets in c:\users\user\anaconda3\lib\site-packages (from jupyter->nb2mail) (7.5.1)
Requirement already satisfied: qtconsole in c:\users\user\anaconda3\lib\site-packages (from jupyter->nb2mail) (4.5.5)
Requirement already satisfied: ipykernel in c:\users\user\anaconda3\lib\site-packages (from jupyter->nb2mail) (5.1.2)
Requirement already satisfied: jupyter-console in c:\users\user\anaconda3\lib\site-packages (from jupyter->nb2mail) (6.0.0)
Requirement already satisfied: nbconvert in c:\users\user\anaconda3\lib\site-packages (from jupyter->nb2mail) (5.6.0)
Requirement already satisfied: nbformat in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (4.4.0)
Requirement already satisfied: tornado>=5.0 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (6.0.3)
Requirement already satisfied: terminado>=0.8.1 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (0.8.2)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (4.3.3)
Requirement already satisfied: prometheus-client in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (0.7.1)
Requirement already satisfied: pyzmq>=17 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (18.1.0)
Requirement already satisfied: Send2Trash in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (1.5.0)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (2.10.3)
Requirement already satisfied: jupyter-core>=4.4.0 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (4.5.0)
Requirement already satisfied: ipython-genutils in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (0.2.0)
Requirement already satisfied: jupyter-client>=5.3.1 in c:\users\user\anaconda3\lib\site-packages (from notebook->jupyter->nb2mail) (5.3.3)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\user\anaconda3\lib\site-packages (from ipywidgets->jupyter->nb2mail) (3.5.1)
Requirement already satisfied: ipython>=4.0.0; python_version >= "3.3" in c:\users\user\anaconda3\lib\site-packages (from ipywidgets->jupyter->nb2mail) (7.8.0)
Requirement already satisfied: pygments in c:\users\user\anaconda3\lib\site-packages (from qtconsole->jupyter->nb2mail) (2.4.2)
Requirement already satisfied: prompt_toolkit<2.1.0,>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from jupyter-console->jupyter->nb2mail) (2.0.10)
Requirement already satisfied: defusedxml in c:\users\user\anaconda3\lib\site-packages (from nbconvert->jupyter->nb2mail) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->jupyter->nb2mail) (1.4.2)
Requirement already satisfied: bleach in c:\users\user\anaconda3\lib\site-packages (from nbconvert->jupyter->nb2mail) (3.1.0)
Requirement already satisfied: testpath in c:\users\user\anaconda3\lib\site-packages (from nbconvert->jupyter->nb2mail) (0.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->jupyter->nb2mail) (0.3)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\user\anaconda3\lib\site-packages (from nbconvert->jupyter->nb2mail) (0.8.4)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\user\anaconda3\lib\site-packages (from nbformat->notebook->jupyter->nb2mail) (3.0.2)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from traitlets>=4.2.1->notebook->jupyter->nb2mail) (4.4.0)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from traitlets>=4.2.1->notebook->jupyter->nb2mail) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from jinja2->notebook->jupyter->nb2mail) (1.1.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\user\anaconda3\lib\site-packages (from jupyter-client>=5.3.1->notebook->jupyter->nb2mail) (2.8.0)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\users\user\anaconda3\lib\site-packages (from jupyter-client>=5.3.1->notebook->jupyter->nb2mail) (223)
Requirement already satisfied: jedi>=0.10 in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->nb2mail) (0.15.1)
Requirement already satisfied: setuptools>=18.5 in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->nb2mail) (41.4.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->nb2mail) (0.4.1)
Requirement already satisfied: backcall in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->nb2mail) (0.1.0)
Requirement already satisfied: pickleshare in c:\users\user\anaconda3\lib\site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->nb2mail) (0.7.5)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt_toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter->nb2mail) (0.1.7)
Requirement already satisfied: webencodings in c:\users\user\anaconda3\lib\site-packages (from bleach->nbconvert->jupyter->nb2mail) (0.5.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter->nb2mail) (19.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\user\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter->nb2mail) (0.15.4)
Requirement already satisfied: parso>=0.5.0 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets->jupyter->nb2mail) (0.5.1)
Building wheels for collected packages: nb2mail
  Building wheel for nb2mail (setup.py): started
  Building wheel for nb2mail (setup.py): finished with status 'done'
  Created wheel for nb2mail: filename=nb2mail-0.6-cp37-none-any.whl size=4352 sha256=8e29c71f5283571e445af5ab505281bba9e81ee74d5ebd719197e02c61cf0b01
  Stored in directory: C:\Users\user\AppData\Local\pip\Cache\wheels\f0\e1\e6\6808aa287dd4d9586e15950163848711c24209ab33687b4518
Successfully built nb2mail
Installing collected packages: nb2mail
Successfully installed nb2mail-0.6
Note: you may need to restart the kernel to use updated packages.